// Shaharlar, joylar, narxlar, ob-havo
const CITIES = {
  samarkand: {
    name: 'Samarqand',
    nameRu: 'Самарканд',
    nameEn: 'Samarkand',
    lat: 39.6542, lng: 66.9597,
    region: 'Samarqand viloyati',
    tags: ['history', 'photo', 'food'],
    dailyCost: { budget: 250000, mid: 500000, comfort: 1000000 },
    highlights: ['Registon', 'Gur-Emir', 'Shohi-Zinda', 'Bibixonim', 'Siyob bozori'],
    bestSeason: 'Mart – May, Sentabr – Noyabr',
  },
  bukhara: {
    name: 'Buxoro', nameRu: 'Бухара', nameEn: 'Bukhara',
    lat: 39.7747, lng: 64.4286,
    region: 'Buxoro viloyati',
    tags: ['history', 'photo', 'food'],
    dailyCost: { budget: 220000, mid: 450000, comfort: 900000 },
    highlights: ['Ark qal\'asi', 'Poi-Kalon', 'Labi-Hovuz', 'Chor Minor'],
    bestSeason: 'Mart – May, Sentabr – Noyabr',
  },
  khiva: {
    name: 'Xiva', nameRu: 'Хива', nameEn: 'Khiva',
    lat: 41.3783, lng: 60.3639,
    region: 'Xorazm viloyati',
    tags: ['history', 'photo'],
    dailyCost: { budget: 200000, mid: 420000, comfort: 850000 },
    highlights: ['Ichan Qal\'a', 'Kalta Minor', 'Juma masjidi'],
    bestSeason: 'Aprel – Iyun, Sentabr – Oktabr',
  },
  tashkent: {
    name: 'Toshkent', nameRu: 'Ташкент', nameEn: 'Tashkent',
    lat: 41.2995, lng: 69.2401,
    region: 'Poytaxt',
    tags: ['shopping', 'food', 'photo'],
    dailyCost: { budget: 300000, mid: 600000, comfort: 1200000 },
    highlights: ['Hazrati Imom', 'Chorsu bozori', 'Amir Temur xiyoboni', 'Metro'],
    bestSeason: 'Butun yil',
  },
  fergana: {
    name: 'Farg\'ona vodiysi', nameRu: 'Ферганская долина', nameEn: 'Fergana Valley',
    lat: 40.3864, lng: 71.7864,
    region: 'Farg\'ona viloyati',
    tags: ['nature', 'food', 'photo'],
    dailyCost: { budget: 200000, mid: 450000, comfort: 900000 },
    highlights: ['Rishton kulolchiligi', 'Marg\'ilon atlaslari', 'Qo\'qon saroyi'],
    bestSeason: 'Aprel – Iyun, Sentabr – Oktabr',
  },
  nukus: {
    name: 'Nukus va Mo\'ynoq', nameRu: 'Нукус и Муйнак', nameEn: 'Nukus & Moynaq',
    lat: 42.4531, lng: 59.6103,
    region: 'Qoraqalpog\'iston',
    tags: ['history', 'nature', 'adventure'],
    dailyCost: { budget: 220000, mid: 480000, comfort: 950000 },
    highlights: ['Savitskiy muzeyi', 'Orol dengizi', 'Kemalar qabristoni'],
    bestSeason: 'Aprel – Iyun, Sentabr – Oktabr',
  },
  zaamin: {
    name: 'Zomin', nameRu: 'Заамин', nameEn: 'Zaamin',
    lat: 39.9643, lng: 68.3967,
    region: 'Jizzax viloyati',
    tags: ['nature', 'adventure'],
    dailyCost: { budget: 180000, mid: 380000, comfort: 750000 },
    highlights: ['Zomin milliy bog\'i', 'Tog\' sayohatlari'],
    bestSeason: 'May – Sentabr',
  },
  charvak: {
    name: 'Chorvoq', nameRu: 'Чарвак', nameEn: 'Charvak',
    lat: 41.6283, lng: 70.0283,
    region: 'Toshkent viloyati',
    tags: ['nature', 'adventure', 'photo'],
    dailyCost: { budget: 250000, mid: 550000, comfort: 1100000 },
    highlights: ['Chorvoq suv ombori', 'Chimyon', 'Parvoz'],
    bestSeason: 'May – Sentabr',
  },
  shahrisabz: {
    name: 'Shahrisabz', nameRu: 'Шахрисабз', nameEn: 'Shakhrisabz',
    lat: 39.0578, lng: 66.8300,
    region: 'Qashqadaryo viloyati',
    tags: ['history', 'photo'],
    dailyCost: { budget: 200000, mid: 400000, comfort: 850000 },
    highlights: ['Oqsaroy', 'Dorut Tilovat', 'Amir Temur haykali'],
    bestSeason: 'Mart – May, Sentabr – Noyabr',
  },
  termez: {
    name: 'Termiz', nameRu: 'Термез', nameEn: 'Termez',
    lat: 37.2242, lng: 67.2783,
    region: 'Surxondaryo viloyati',
    tags: ['history', 'nature'],
    dailyCost: { budget: 180000, mid: 380000, comfort: 750000 },
    highlights: ['Fayoztepa', 'Termiz muzeyi', 'Buddist yodgorliklari'],
    bestSeason: 'Mart – May, Sentabr – Noyabr',
  },
  karshi: {
    name: 'Qarshi', nameRu: 'Карши', nameEn: 'Karshi',
    lat: 38.8667, lng: 65.8000,
    region: 'Qashqadaryo viloyati',
    tags: ['history', 'food'],
    dailyCost: { budget: 180000, mid: 380000, comfort: 780000 },
    highlights: ['Qashqadaryo', 'Mahalliy bozorlar'],
    bestSeason: 'Mart – May, Sentabr – Noyabr',
  },
  urgench: {
    name: 'Urganch', nameRu: 'Ургенч', nameEn: 'Urgench',
    lat: 41.5500, lng: 60.6333,
    region: 'Xorazm viloyati',
    tags: ['history', 'food'],
    dailyCost: { budget: 200000, mid: 420000, comfort: 850000 },
    highlights: ['Xiva yo\'li', 'Xorazm madaniyati'],
    bestSeason: 'Aprel – Iyun, Sentabr – Oktabr',
  },
};

const PLACES = [
  // Samarqand
  { city: 'samarkand', name: 'Registon maydoni', type: 'history', lat: 39.6547, lng: 66.9758, rating: 4.9, desc: '3 madrasa ansambli — Sharqning eng mashhur maydoni' },
  { city: 'samarkand', name: 'Gur-Emir maqbarasi', type: 'history', lat: 39.6481, lng: 66.9689, rating: 4.9, desc: 'Amir Temur maqbarasi' },
  { city: 'samarkand', name: 'Shohi-Zinda', type: 'history', lat: 39.6640, lng: 66.9878, rating: 4.8, desc: 'Maqbaralar ko\'chasi' },
  { city: 'samarkand', name: 'Siyob bozori', type: 'food', lat: 39.6620, lng: 66.9765, rating: 4.6, desc: 'An\'anaviy bozor' },
  // Buxoro
  { city: 'bukhara', name: 'Ark qal\'asi', type: 'history', lat: 39.7753, lng: 64.4106, rating: 4.8, desc: 'Qadimiy hukmdorlar qarorgohi' },
  { city: 'bukhara', name: 'Poi-Kalon', type: 'history', lat: 39.7756, lng: 64.4147, rating: 4.9, desc: 'Kalon minor va masjid' },
  { city: 'bukhara', name: 'Labi-Hovuz', type: 'food', lat: 39.7731, lng: 64.4206, rating: 4.7, desc: 'Mashhur ansambl va choyxonalar' },
  // Xiva
  { city: 'khiva', name: 'Ichan Qal\'a', type: 'history', lat: 41.3783, lng: 60.3639, rating: 4.9, desc: 'Ichki shahar — muzey' },
  { city: 'khiva', name: 'Kalta Minor', type: 'history', lat: 41.3784, lng: 60.3629, rating: 4.7, desc: 'Moviy minora' },
  // Toshkent
  { city: 'tashkent', name: 'Chorsu bozori', type: 'food', lat: 41.3266, lng: 69.2365, rating: 4.7, desc: 'Toshkentning yuragi' },
  { city: 'tashkent', name: 'Hazrati Imom majmuasi', type: 'history', lat: 41.3381, lng: 69.2397, rating: 4.8, desc: 'Islomiy markaz' },
  { city: 'tashkent', name: 'Amir Temur xiyoboni', type: 'photo', lat: 41.3111, lng: 69.2797, rating: 4.6, desc: 'Markaziy xiyobon' },
  // Farg'ona
  { city: 'fergana', name: 'Rishton kulolchilik markazi', type: 'photo', lat: 40.3561, lng: 71.2825, rating: 4.8, desc: 'Mashhur kulolchilik' },
  { city: 'fergana', name: 'Qo\'qon saroyi', type: 'history', lat: 40.5286, lng: 70.9425, rating: 4.7, desc: 'Xudoyorxon o\'rdasi' },
  // Nukus
  { city: 'nukus', name: 'Savitskiy muzeyi', type: 'museum', lat: 42.4622, lng: 59.6128, rating: 4.9, desc: 'Avangard san\'at kolleksiyasi' },
  { city: 'nukus', name: 'Mo\'ynoq kemalar qabristoni', type: 'adventure', lat: 43.7683, lng: 59.0272, rating: 4.7, desc: 'Orol dengizi fojiasi' },
  // Chorvoq
  { city: 'charvak', name: 'Chorvoq suv ombori', type: 'nature', lat: 41.6283, lng: 70.0283, rating: 4.7, desc: 'Ko\'l va tog\' manzarasi' },
  { city: 'charvak', name: 'Chimyon', type: 'food', lat: 41.5736, lng: 70.0458, rating: 4.6, desc: 'Tog\' dam olish maskani' },
];

const CHECKLIST_DEFAULT = [
  { id: 'docs', uz: 'Hujjatlar va ID karta', ru: 'Документы и ID', en: 'Documents & ID' },
  { id: 'phone', uz: 'Telefon va quvvatlagich', ru: 'Телефон и зарядка', en: 'Phone & charger' },
  { id: 'clothes', uz: 'Kiyim-kechak', ru: 'Одежда', en: 'Clothes' },
  { id: 'meds', uz: 'Dori-darmon va gigiyena', ru: 'Лекарства и гигиена', en: 'Meds & hygiene' },
  { id: 'hotel', uz: 'Mehmonxona band qilish', ru: 'Бронь отеля', en: 'Hotel booking' },
  { id: 'tickets', uz: 'Transport chiptalari', ru: 'Билеты на транспорт', en: 'Transport tickets' },
  { id: 'money', uz: 'Naqd pul yoki bank kartasi', ru: 'Наличные или карта', en: 'Cash or card' },
  { id: 'powerbank', uz: 'Powerbank', ru: 'Повербанк', en: 'Powerbank' },
  { id: 'snacks', uz: 'Suv va yengil tamaddi', ru: 'Вода и перекус', en: 'Water & snacks' },
];

const WEATHER = {
  samarkand: { summer: 34, winter: 5, spring: 18, autumn: 17, best: 'Apr–May, Sep–Oct' },
  bukhara:   { summer: 38, winter: 4, spring: 19, autumn: 18, best: 'Apr–May, Sep–Oct' },
  khiva:     { summer: 38, winter: 2, spring: 19, autumn: 17, best: 'Apr–Jun, Sep–Oct' },
  tashkent:  { summer: 36, winter: 6, spring: 18, autumn: 17, best: 'Butun yil' },
  fergana:   { summer: 35, winter: 4, spring: 18, autumn: 17, best: 'Apr–Jun, Sep–Oct' },
  nukus:     { summer: 38, winter: -3, spring: 16, autumn: 15, best: 'Apr–Jun, Sep–Oct' },
  zaamin:    { summer: 28, winter: 0, spring: 14, autumn: 13, best: 'May–Sep' },
  charvak:   { summer: 30, winter: 1, spring: 15, autumn: 14, best: 'May–Sep' },
  shahrisabz:{ summer: 35, winter: 5, spring: 18, autumn: 17, best: 'Apr–May, Sep–Oct' },
  termez:    { summer: 40, winter: 8, spring: 20, autumn: 19, best: 'Mar–May, Sep–Nov' },
  karshi:    { summer: 36, winter: 6, spring: 18, autumn: 17, best: 'Apr–May, Sep–Oct' },
  urgench:   { summer: 38, winter: 2, spring: 19, autumn: 17, best: 'Apr–Jun, Sep–Oct' },
};

const QUIZ_QUESTIONS = [
  { uz: 'Sizni ko\'proq nima qiziqtiradi?', ru: 'Что вас больше интересует?', en: 'What interests you most?',
    options: [
      { uz: 'Qadimiy tarix', ru: 'Древняя история', en: 'Ancient history', tags: ['history'] },
      { uz: 'Tabiat va tog\'lar', ru: 'Природа и горы', en: 'Nature & mountains', tags: ['nature'] },
      { uz: 'Taomlar', ru: 'Еда', en: 'Food', tags: ['food'] },
      { uz: 'Sarguzasht', ru: 'Приключения', en: 'Adventure', tags: ['adventure'] },
    ]},
  { uz: 'Qancha vaqtga bormoqchisiz?', ru: 'На сколько едете?', en: 'How long?',
    options: [
      { uz: '1–2 kun', ru: '1–2 дня', en: '1–2 days', tags: ['short'] },
      { uz: '3–5 kun', ru: '3–5 дней', en: '3–5 days', tags: ['mid'] },
      { uz: 'Bir hafta', ru: 'Неделя', en: 'One week', tags: ['long'] },
      { uz: 'Ko\'proq', ru: 'Больше', en: 'More', tags: ['long'] },
    ]},
  { uz: 'Budjetingiz qanday?', ru: 'Ваш бюджет?', en: 'Your budget?',
    options: [
      { uz: 'Tejamkor', ru: 'Экономный', en: 'Budget', tags: ['budget'] },
      { uz: 'O\'rtacha', ru: 'Средний', en: 'Mid', tags: ['mid'] },
      { uz: 'Qulay', ru: 'Комфортный', en: 'Comfort', tags: ['comfort'] },
      { uz: 'Premium', ru: 'Премиум', en: 'Premium', tags: ['premium'] },
    ]},
  { uz: 'Kim bilan?', ru: 'С кем?', en: 'With whom?',
    options: [
      { uz: 'Yolg\'iz', ru: 'Один', en: 'Solo', tags: ['solo'] },
      { uz: 'Juftlik', ru: 'Пара', en: 'Couple', tags: ['couple'] },
      { uz: 'Oila', ru: 'Семья', en: 'Family', tags: ['family'] },
      { uz: 'Do\'stlar', ru: 'Друзья', en: 'Friends', tags: ['friends'] },
    ]},
  { uz: 'Nima muhim?', ru: 'Что важно?', en: 'What matters?',
    options: [
      { uz: 'Suratga olish', ru: 'Фотографии', en: 'Photos', tags: ['photo'] },
      { uz: 'Xarid', ru: 'Шоппинг', en: 'Shopping', tags: ['shopping'] },
      { uz: 'Dam olish', ru: 'Отдых', en: 'Relax', tags: ['relax'] },
      { uz: 'Yangi taassurot', ru: 'Новые впечатления', en: 'New experiences', tags: ['adventure'] },
    ]},
];